version: '3.0'
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - "3100:8111"
    volumes:
      - ./server/datadir:/data/teamcity_server/datadir
      - ./server/logs:/opt/teamcity/logs
  #    networks:
  #      - teamcity

  teamcity-agent:
    image: yurihyuga/teamcity-node-agent1
    links:
      - teamcity-server:teamcity-server
    build:
      context: ./agent
    volumes:
      - ./agent/conf:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=teamcity-server:8111
#     networks:
#       - teamcity

# networks:
#   teamcity:
#     external: true